import * as SubframeCore from '@subframe/core'

export const twClassNames = SubframeCore.createTwClassNames([
  'text-caption',
  'text-caption-small',
  'text-body',
  'text-body-bold',
  'text-heading-3',
  'text-heading-2',
  'text-heading-1',
  'text-monospace-body',
  'text-subheader',
  'text-display-text-extra-large',
  'text-display-text-large',
  'text-display-text-small',
  'text-overline',
  'text-subtitle',
  'text-overtitle',
  'text-button-small',
  'text-body-large',
  'text-button-large',
  'text-body-small',
  'text-text-button',
  'text-heading-4',
  'text-display-text-medium',
  'text-button-medium',
])
