packages:
  - apps/*
  - packages/*
  - services/*
  - services/cloud-functions/functions

onlyBuiltDependencies:
  - "@firebase/util"
  - "@tailwindcss/oxide"
  - protobufjs
  - sharp
  - unrs-resolver
